MIN_VISIBILITY = 0.5
SMOOTHING_WINDOW = 5

# COM proxy blend
COM_HIP_WEIGHT = 0.7

# Coaching thresholds
OUTSIDE_SKI_OFFSET_THRESHOLD = 0.35
COM_CENTERED_RATIO_THRESHOLD = 0.12
ANGULATION_DEG_THRESHOLD = 8.0
LEG_TILT_MIN_DEG = 10.0
LATE_COM_RATIO_THRESHOLD = 0.7

# Turn detection
TURN_MIN_FRAMES = 20
TURN_APEX_WINDOW_RATIO = 0.1

# Crop settings
CROP_MARGIN_X = 0.30
CROP_MARGIN_Y = 0.25
CROP_EMA_ALPHA = 0.35
CROP_MIN_POINTS = 4

# Target tracking
TRACK_DETECT_INTERVAL = 3
TRACK_MATCH_SCORE_THRESHOLD = 0.26
TRACK_MISS_STREAK_TO_LOST = 3
TRACK_HIT_STREAK_TO_LOCK = 2
RENDER_MAX_UPSCALE = 1.8
RENDER_SIZE_PERCENTILE = 75
RENDER_MIN_CROP_WIDTH = 360
RENDER_MIN_CROP_HEIGHT = 540
RENDER_WARMUP_FRAMES = 24
RENDER_WARMUP_SCALE = 1.35
POSE_CROP_MARGIN_X = 0.14
POSE_CROP_MARGIN_Y = 0.18
POSE_DRIFT_MAX_CENTER_DIST_NORM = 0.30
POSE_DRIFT_HOLD_FRAMES = 10

# Person detection backend
PERSON_DETECTOR_BACKEND = "auto"  # auto | yolo | hog
YOLO_MODEL = "yolov8n.pt"
YOLO_CONF_THRESHOLD = 0.25
YOLO_IOU_THRESHOLD = 0.45

# Annotated video encoding order (first successful codec is used)
# Reliability-first default avoids OpenH264 runtime mismatches.
VIDEO_CODEC_CANDIDATES = ["mp4v"]
